services:
  # Next
  next:
    build:
      context: .
      dockerfile: ./docker/dev/next/next.Dockerfile
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json

  # Postgres
  db:
    image: postgres
    env_file:
      - path: .env.local
      - path: .env.development
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/dev/postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d/

volumes:
  db:
    driver: local
