import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import Sidebar from "@/components/Sidebar/Sidebar";
import "./tailwind.css";
import styles from "./layout.module.scss";

const font = Manrope({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} ${styles["layout"]}`}>
        <Sidebar />
        <main>{children}</main>
      </body>
    </html>
  );
}
